### ISSUE TITLE
 Blocks of text separated by one or more blank lines will be parsed as paragraphs.  If you want to create a line break, end a line with two or more spaces, then hit Return/Enter.

### ISSUE THREAD

**Issue by mohnd89** [cmlh/Maltego-Facebook#19]

**Comment by mohnd89** [comment]
Blocks of text separated by one or more blank lines will be parsed as paragraphs.

If you want to create a line break, end a line with two or more spaces, then hit Return/Enter.

**Comment by cmlh** [comment]
@mohnd89 Please let me know if I can be of assistance?
